// Import the localFont function from Next.js for loading custom fonts
import localFont from "next/font/local";
// Import global CSS styles
import "./globals.css";

// Load the Geist Sans variable font
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900", // Supports weights from 100 to 900
});

// Load the Geist Mono variable font
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900", // Supports weights from 100 to 900
});

// Define metadata for the application
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // Apply the custom fonts and antialiasing to the body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Render the child components */}
        {children}
      </body>
    </html>
  );
}
